### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Snowplow\RefererParser\Parser'

### ISSUE THREAD

**Issue by alejandronb** [GoteoFoundation/goteo#149]
I've found this error with several scenarios: docker, vagrant, I've tried installing on my own machine too and I always have this error. I'll put the Vagrant scenario:

 ```
    default: 
    default: To start a development server run these commands:
    default: 
    default: vagrant ssh
    default: grunt serve
    default: 
    default: Then, your browser should be opened automatically pointing
    default: at http://localhost:8081 
    default: 
    default: Optionally, the internal Vagrant's Apache server is configured to serve
    default: the content of the /home/vagrant/goteo/dist folder
    default: This allows you to test the distribution package.
    default: To test it, you NEED TO RUN these commands:
    default: 
    default: vagrant ssh
    default: grunt build:dist
    default: 
    default: Then, point your browser to http://localhost:8080
➜  goteo git:(master) ✗ vagrant ssh
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-173-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


0 packages can be updated.
0 updates are security updates.

New release '18.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


vagrant@ubuntu-xenial:~/goteo$ grunt serve
>> Using Host from settings: 0.0.0.0
>> Using local port from settings: 8081
>> Using livePort from settings: 35729
>> CURRENT DIR /home/vagrant/goteo
>> using PHP php-fpm

Running "serve" task

Running "clean:server" (clean) task
>> 1111 paths cleaned.

Running "copy:devel" (copy) task
Created 588 directories, copied 3039 files

Running "copy:plugins:devel" (copy:plugins) task

Running "sass:devel" (sass) task

Running "php:livereload" (php) task
PHP 7.0.33-0ubuntu0.16.04.9 Development Server started at Thu Feb  6 06:58:48 2020
Listening on http://0.0.0.0:8081
Document root is /home/vagrant/goteo/.tmp
Press Ctrl-C to quit.
[2020-02-06 07:58:50] main.INFO: Matched route "home". {"route_parameters":{"_controller":"Goteo\\Controller\\IndexController::indexAction","_route":"home"},"request_uri":"http://0.0.0.0:8081/"} {"memory_usage":"6 MB","mhash":"matched-route-home","uid":"92a52b1b","session":"env2bcrv","token":"92a52b1b","ip":"127.0.0.1","method":"HEAD","user":"","lang":"es","currency":"EUR"}
[Thu Feb  6 06:58:50 2020] PHP Fatal error:  Uncaught Error: Class 'Snowplow\RefererParser\Parser' not found in /home/vagrant/goteo/src/Goteo/Util/Origins/Parser.php:66
Stack trace:
#0 /home/vagrant/goteo/src/Goteo/Application/EventListener/OriginListener.php(49): Goteo\Util\Origins\Parser->getReferer()
#1 [internal function]: Goteo\Application\EventListener\OriginListener->onRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /home/vagrant/goteo/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /home/vagrant/goteo/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#4 /home/vagrant/goteo/vendor/symfony/http-kernel/HttpKernel.php(116): Symf in /home/vagrant/goteo/src/Goteo/Util/Origins/Parser.php on line 66
```

When I run tests the error appears too:
```There were 3 errors:

1) Goteo\Application\Tests\AppTest::testApp
PHP Fatal error:  Method PHPUnit_Framework_ExceptionWrapper::__toString() must not throw an exception, caught ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php on line 0
PHP Stack trace:
PHP   1. {main}() /home/vagrant/goteo/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/vagrant/goteo/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_TextUI_ResultPrinter->printResult() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:523
PHP   6. PHPUnit_TextUI_ResultPrinter->printErrors() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:182
PHP   7. PHPUnit_TextUI_ResultPrinter->printDefects() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:277
PHP   8. PHPUnit_TextUI_ResultPrinter->printDefect() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:228
PHP   9. PHPUnit_TextUI_ResultPrinter->printDefectTrace() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:241

Fatal error: Method PHPUnit_Framework_ExceptionWrapper::__toString() must not throw an exception, caught ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php on line 0

Call Stack:
    0.0004     353920   1. {main}() /home/vagrant/goteo/vendor/phpunit/phpunit/phpunit:0
    0.0479    1210752   2. PHPUnit_TextUI_Command::main() /home/vagrant/goteo/vendor/phpunit/phpunit/phpunit:52
    0.0479    1210864   3. PHPUnit_TextUI_Command->run() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/Command.php:116
    3.1832   24983104   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/Command.php:186
   52.0421   42038000   5. PHPUnit_TextUI_ResultPrinter->printResult() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:523
   52.0422   42038000   6. PHPUnit_TextUI_ResultPrinter->printErrors() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:182
   52.0422   42038000   7. PHPUnit_TextUI_ResultPrinter->printDefects() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:277
   52.0422   42038000   8. PHPUnit_TextUI_ResultPrinter->printDefect() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:228
   52.0422   42038000   9. PHPUnit_TextUI_ResultPrinter->printDefectTrace() /home/vagrant/goteo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php:241
```

**Comment by davidbeig** [comment]
Hi @alejandronb,

Sorry for not answering at the time you wrote us. We solved this issue a year ago changing the version that the composer was pointing for the snowplow library.

```
"snowplow/referer-parser": "0.2.0"
```

https://github.com/GoteoFoundation/goteo/blob/devel/composer.json
