### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Snowplow\RefererParser\Parser' not found

### ISSUE THREAD

**Issue by yoghioctopus** [GoteoFoundation/goteo#158]
Fatal error: Uncaught Error: Class 'Snowplow\RefererParser\Parser' not found in /home/u379094006/domains/agroplus.co.id/agroplus/src/Goteo/Util/Origins/Parser.php:66 Stack trace: #0 /home/u379094006/domains/agroplus.co.id/agroplus/src/Goteo/Application/EventListener/OriginListener.php(49): Goteo\Util\Origins\Parser->getReferer() #1 [internal function]: Goteo\Application\EventListener\OriginListener->onRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /home/u379094006/domains/agroplus.co.id/agroplus/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 /home/u379094006/domains/agroplus.co.id/agroplus/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Compo in /home/u379094006/domains/agroplus.co.id/agroplus/src/Goteo/Util/Origins/Parser.php on line 66

**Comment by davidbeig** [comment]
Hi @yoghioctopus!

As I have answered in another issue #149. We had a problem with this library and had to change in the composer file the release we were referencing. 
In the latest release of Goteo you can find it has changed. 

Could you try now?
