### ISSUE TITLE
goteo on minikube cluster

### ISSUE THREAD

**Issue by yoan34** [GoteoFoundation/goteo#306]
hi,
For the needs of our start-up, we would like to launch Goteo on a minikube cluster.
Here are the steps I took:
- `minikube mount .:/home/docker/application` to add the application in the minikube.
- `kompose convert` to generate the K8s files, delete all **PersistentVolumeClaim** file and use **emptyDir: {}** instead.
- `kubectl create configmap nginx-configuration --from-file ./docker/nginx/nginx.conf` to be able to reference the nginx configuration file.
- In **webserver-deployment.yaml** I mount the application in **/application** and change the **default.conf** with the configmap **nginx-configuration**.
- `kubectl create configmap php-configuration --from-file ./docker/php/php-ini-overrides.ini` to be able to reference the php configuration file.
- In **php-deployment.yml** I mount the application in **/application** and change file **99-overrides.ini** with the configmap **php-configuration**.
- In **php-deployment.yml**, I add an environnement variable `GOTEO_CONFIG_FILE=application/config/settings.yml docker/up`

has anyone tried putting goteo on the minikube cluster?

Ouput of `kubectl get pods`:
```
NAME                         READY   STATUS             RESTARTS         AGE
geoip-6f466d7dd6-fql9x       0/1     CrashLoopBackOff   11 (2m27s ago)   34m
mailhog-7f58cfcdf7-vz8hw     1/1     Running            0                34m
mariadb-6878cf9444-qzqkj     1/1     Running            0                34m
php-5cbf8458-5j7ck           0/1     CrashLoopBackOff   11 (72s ago)     34m
webserver-556c66bc6d-6cmng   0/1     CrashLoopBackOff   11 (101s ago)    34m
```

Show logs of webserver `kubectl logs webserver-556c66bc6d-6cmng`
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/12/07 15:14:55 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/nginx.conf:32
nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/nginx.conf:32

```

Show logs of webserver `kubectl logs php-5cbf8458-5j7ck`
```
docker/php/init.sh: line 61: [: application/config/settings.yml: binary operator expected
usermod: no changes
docker/php/init.sh: line 9: application/config/settings.yml: No such file or directory
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package amphp/artax is abandoned, you should avoid using it. Use amphp/http-client instead.
Package paypal/adaptivepayments-sdk-php is abandoned, you should avoid using it. No replacement was suggested.
Package paypal/sdk-core-php is abandoned, you should avoid using it. No replacement was suggested.
Package react/http-client is abandoned, you should avoid using it. Use react/http instead.
Package symfony/inflector is abandoned, you should avoid using it. Use use `EnglishInflector` from the String component instead instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/plugin-mock is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
The disk hosting /application/vendor is full, this may be the cause of the following exception

                                                                                                                                 
  [RuntimeException]                                                                                                             
  File at "/application/vendor/jdorn/file-system-cache/lib/FileSystemCache.php" does not exist, check your classmap definitions  
                                                                                                                                 

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

PHP Fatal error:  Uncaught Goteo\Application\Config\ConfigException: Database misconfiguration: SQLSTATE[HY000] [2002] No such file or directory in /application/src/Goteo/Core/DB.php:71
Stack trace:
#0 /application/src/Goteo/Core/Model.php(81): Goteo\Core\DB->__construct()
#1 /application/src/Goteo/Application/Config.php(127): Goteo\Core\Model::factory()
#2 /application/bin/console(33): Goteo\Application\Config::load()
#3 {main}
  thrown in /application/src/Goteo/Core/DB.php on line 71

Fatal error: Uncaught Goteo\Application\Config\ConfigException: Database misconfiguration: SQLSTATE[HY000] [2002] No such file or directory in /application/src/Goteo/Core/DB.php on line 71

Goteo\Application\Config\ConfigException: Database misconfiguration: SQLSTATE[HY000] [2002] No such file or directory in /application/src/Goteo/Core/DB.php on line 71

Call Stack:
    0.0011     408584   1. {main}() /application/bin/console:0
    0.3025    2237776   2. Goteo\Application\Config::load($config_file = '/application/bin/../config/settings.yml') /application/bin/console:33

Fatal error: ################################################
Please configure a settings file with this name:
application/config/settings.yml docker/up

You can use the config/demo-settings.yml as a sample file
################################################

grunt build:tmp failed!
Aborting
```

**Comment by carlos-mg89** [comment]
Hi @yoan34, unfortunately we've had no time to use Goteo outside of Docker. And is not in our short or mid-term plans to do so.

Feel free to give it a chance with this infrastructure technology. It allows you for scaling as well.
