### ISSUE TITLE
Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "routes"

### ISSUE THREAD

**Issue by ghost** [GoteoFoundation/goteo#525]
2023/03/08 09:39:09 [error] 32536#32536: *70 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "routes". in /home/wwwroot/goteo/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:95
Stack trace:
#0 /home/wwwroot/goteo/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(69): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get()
#1 /home/wwwroot/goteo/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(206): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get()
#2 /home/wwwroot/goteo/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(177): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString()
#3 /home/wwwroot/goteo/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(167): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue()

---------------------------------------

Hi creator, I have an issue.
I have change db connection and it is successful. That means the db is correct. I have seen all tables.

I follow this doc.
https://goteofoundation.github.io/goteo/docs/install.html 

Please help me. Thanks

Tom

**Comment by davidbeig** [comment]
Hello! :)

I think i might need some more information about your problem. But seems like it's not loading correctly the routes of the project. Could you execute `docker/up` correctly? Can you see anything in localhost:8081?

**Comment by ghost** [comment]
> Hello! :)
> 
> I think i might need some more information about your problem. But seems like it's not loading correctly the routes of the project. Could you execute `docker/up` correctly? Can you see anything in localhost:8081?

Thanks for your quick answer. I don`t use docker.
https://goteofoundation.github.io/goteo/docs/install.html
I follow this guide. And have finished all steps.

My nginx:
server {
    listen 80;
    charset utf-8;
    root /home/wwwroot/goteo/dist/index.php;

   location / {
        index que.php  internal.php index.php index.html index.htm sqe.php;

	if (!-e $request_filename) {
   		rewrite  ^(.*)$  /index.php?s=/$1  last;
    	}

  }
  location ~ \.php {
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    fastcgi_read_timeout 300;
    include        fastcgi_params;
    fastcgi_param  APP_ENV test;
  }
}


-------------
I don`t visit 8081 port. I have a domain and I visit 80 port.
Should I viisit 8081 port?

Thanks.

**Comment by ghost** [comment]
> Hello! :)
> 
> I think i might need some more information about your problem. But seems like it's not loading correctly the routes of the project. Could you execute `docker/up` correctly? Can you see anything in localhost:8081?

When I visit this page(Our domain).
----
This page isn’t working
192.248.173.xxx
is currently unable to handle this request.
HTTP ERROR 500

And I list log: 
And the log I have posted you can see that.

**Comment by davidbeig** [comment]
Sorry, i though you were testing it in your local machine, that's why i asked about if you used docker/up and if you visited the port 8081, that's the one mapping port 80 in the docker container.

Did you check the example nginx configuration inside the repository?

Could you send us the domain where you have the instance running?

**Comment by ghost** [comment]
> Sorry, i though you were testing it in your local machine, that's why i asked about if you used docker/up and if you visited the port 8081, that's the one mapping port 80 in the docker container.
> 
> Did you check the example nginx configuration inside the repository?
> 
> Could you send us the domain where you have the instance running?


Hi,

This is my nginx conf file.
Our site:  http://192.248.173.74:8081
You can visit this link.

I follow this doc:
http://goteofoundation.github.io/goteo/docs/install.html

I did not used docker. Maybe I ask one question, should I use docker if it is on produciton ? 

`server {
    listen 8081;
    charset utf-8;
    root /home/wwwroot/goteo/dist/index.php;

   location / {
        index que.php  internal.php index.php index.html index.htm sqe.php;

	if (!-e $request_filename) {
   		rewrite  ^(.*)$  /index.php?s=/$1  last;
    	}

  }
  location ~ \.php {
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    fastcgi_read_timeout 300;
    include        fastcgi_params;
  }
}`

**Comment by ghost** [comment]
The db is correct and it has been created all tables.
So I think it maybe caused be some php class or component.

Thanks your help again.

**Comment by Philippe80120** [comment]
Hi,

I have the problem during installation, have you found a solution?
Thanks

**Comment by davidbeig** [comment]
It's not something that we face normally. Could you check if the vendor folder has the same user as the application? Maybe you downloaded it with `sudo` and the application can't load the files and then it isn't able to read all the components.

**Comment by Philippe80120** [comment]
Thanks for the response, I checked and the permissions on the files and folders are correct. I'm going to start the installation from scratch.
For this installation I copied the files from my docker environment to install them on an Nginx/Php/Mariadb server, I may have missed a step...
